### ISSUE TITLE
pushing code

### ISSUE THREAD

**Issue by slantedvision** [cognitionIT/PS-NITRO#1]
Esther, you mentioned during Synergy that this was the link to your powershell content.  Can you do a push of the powershell code that you created here?

**Comment by cognitionIT** [comment]
I'm really sorry it is taking me longer than expected to unbox the homelab in the new house and get the latest code from my dev machine :-(
I have uploaded an older version from a backup I found, but the sample scripts will have to wait.

Looks like I'll need some more time to give the dev machine a temp location in the new house and get that latest code from it.

Hope the version I uploaded is helping! Feel free to contact me for me questions you might have.

Cheers,
Esther

**Comment by cognitionIT** [comment]
I have uploaded the latest version of my NITRO PowerShell Module and the sample scripts used for the Citrix Synergy presentation.

Have fun and looking forward to any feedback on the code :-)
