### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by olljanat** [cognitionIT/PS-NITRO#2]
The original project (https://github.com/santiagocardenas/netscaler-configuration) contains information that it is shared without any limitations.

Can you add same disclaimer or Apache 2.0 license to this one so this module can be combined with https://github.com/devblackops/NetScaler which is available through PowerShell Gallery?

**Comment by cognitionIT** [comment]
Hi Olli,

Thanks for pointing out that I need to add a disclaimer to the project. As I'm still new to GitHub and trying to figure it all out, I'll look into it and work on the disclaimer (and proper PowerShell Module creation) in the next couple of months. Any pointers are greatly appreciated!

Cheers,
Esther

**Comment by cognitionIT** [comment]
Ollie, I've added the GNUv3 license to the repository, so hopefully that helps you out on the merging part?
